### ISSUE TITLE
Suggestions for Add a Gene Ontology Term to this Protein

### ISSUE THREAD

**Issue by stuppie** [putmantime/CMOD.Django#12]
Add a dropdown list of evidence codes and/or validate the input.
Add a `?` link to the evidence code [documentation](http://www.candidagenome.org/cgi-bin/GO/goEvidence.pl)
Have the `Gene Ontology Term` field show the name of the selected value instead of the QID

**Comment by putmantime** [comment]
Great suggestions thank you...all are implemented.
