### ISSUE TITLE
Handle HTTP error code 429 "Too many requests" 

### ISSUE THREAD

**Issue by cmdcolin** [putmantime/CMOD.Django#25]
Sometimes when loading the jbrowse on wikigenomes.org, the track or some areas of the track will not load (continue to say "Loading...") and the javascript error console will show something like

    XMLHttpRequest cannot load https://query.wikidata.org/sparql?query=PREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fw…rt)%20%3E%20543971%20%7C%7C%20xsd%3Ainteger(%3Fend)%20%3C%20511027))%20%7D. 
    No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://wikigenomes.org' is therefore not allowed access. 
    The response had HTTP status code 429.

The error code 429 appears be "too many requests"

It's possible it could re-request the content if this message is received

**Comment by putmantime** [comment]
@cmdcolin Picking up from issue #26 concerns.   Too many requests are being made as you scroll through the genome in Jbrowse, as you noticed in Jan.  We were running into rate limit errors with the Wikidata SPARQL endpoint because every scroll would send between 15-40 requests.   The modifications I have made use 1 sparql query to retrieve all the features, then writes them to a .gff on my server that JBrowse then reads.  Happy to discuss better ways to do this, but I do like the idea of a buffer between the wikidata sparql endpoint and the interface.

**Comment by cmdcolin** [comment]
Gotcha. I just remembered this issue.

I think it is actually much better to query the wikidata endpoint directly rather than use a "buffer", and I think that there are reasonable ways to fix the HTTP error code 429 on the client side. My solution would be

1) get more data per query. Currently the wikigenomes SPARQL queries are getting a small amount of data (one for each "visual block" that is displayed in jbrowse) so that results in many queries (related to https://github.com/GMOD/jbrowse/issues/395) but I have a solution in my head that would make this more optimized

2) simply make a function that retries a query if it fails with status 429 for example

**Comment by cmdcolin** [comment]
It is actually even possible to make the "1 sparql query retrieve all features" on client side instead of server side too :) similar to my "get more data per query" but I think just "bigger amount of data per query" rather than "all genes in one query" is a little more scalable as client side solution.

**Comment by putmantime** [comment]
Right.
I wouldn't want to do all genes because I think that is where we will run into performance issues with eukaryotes especially.    I could add 10k or so basepairs on each side of the sqarql filter range and see if that helps.

**Comment by cmdcolin** [comment]
I was able to design a sort of augmented sparql query system that I think handles this pretty well.

It basically does the idea of "adding 10k" base pairs, with a little extra smarts on top

Here is how it works

- it just fetches the features in blocks, e.g. 0-100000, 100000-200000, 300000-400000, etc as needed, only around where the current view is
- caches those results using LRUCache (common around other parts of jbrowse codebase) so that it doesn't do repeat queries on scroll
- also will retry query if there is a 429 error

This together greatly reduces number of wikidata queries :)

**Comment by cmdcolin** [comment]
PR pending

**Comment by putmantime** [comment]
This is great! Thank you!  Will be moving over to wikigenomes version 2 shortly so we should incorporate it there: https://github.com/putmantime/WikiGenomes.org.

**Comment by cmdcolin** [comment]
xref https://github.com/putmantime/WikiGenomes.org/pull/1

**Comment by cmdcolin** [comment]
Since this is now merged maybe we can close this :)!
