### ISSUE TITLE
All the wikidata annotations for genes have been deleted

### ISSUE THREAD

**Issue by cmdcolin** [putmantime/CMOD.Django#27]
I am not sure if I am mistaken, but it appears that almost all data has been deleted that were dynamically loaded from wikidata and the SPARQL queries on jbrowse no longer any results (to be actually accurate, there is one gene on helicobacter still that has this entity link https://www.wikidata.org/wiki/Q21629632)

aside from this example many deletions appear to have taken place?

wondering what we should do

**Comment by putmantime** [comment]
Hi Colin,
Working on it.  The WD model has changed.  I have tried to update the sparql query in the Wikidata plugin, then run setup.sh, then restarted and the changes aren’t updating.  What am I missing?
Tim

**Comment by cmdcolin** [comment]
You may need to clear browser cache after making changes to the config to see the updates

**Comment by putmantime** [comment]
Ok thanks, I thought I was clearing the cache but didn't work until I totally disabled it.  Production is  fixed now.  Thanks for headsup.  Repo has changed to https://github.com/SuLab/WikiGenomes.org.  I have some work to do to get everything in sync with production.  Standby for those changes in the next few days

**Comment by cmdcolin** [comment]
Cool :) if possible maybe this repo can just be deleted or archived ? anyways good work!
